### ISSUE TITLE
SCOCO dataset

### ISSUE THREAD

**Issue by borsukvasyl** [vinthony/s2am#10]
Could you share link to the SCOCO dataset, please? Link from readme is not working (https://uofmacau-my.sharepoint.com/:u:/g/personal/yb87432_umac_mo/EZ4-Qpk-iHFLrTfZKIzAivoBn_Jm8mMkZ6EiqAsz4M0Uhg?e=uqShf3)

**Comment by vinthony** [comment]
Hi, thanks for your attention.
It seems the OneDrive only can directly share the file<5GB.
I will deal with this issue when I have time.

However, if you want to evaluate the algorithm, you can try this dataset https://github.com/bcmi/Image_Harmonization_Datasets

**Comment by borsukvasyl** [comment]
Hi, thank you for your reply. I will try that data

**Comment by vinthony** [comment]
updated.
