### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by mShuvi** [vinthony/s2am#11]
Hey,

Can you please upload your trained models?

Thanks!

**Comment by vinthony** [comment]
Sure, I will update the pre-trained model soon.

**Comment by vinthony** [comment]
Hi, thanks for your attention.

A simple online demo has been hosted in [google colab](https://colab.research.google.com/drive/1UTjyi0J1F2mjc9rf9ZbFUOL2_kkZmdlQ?usp=sharing).

The pre-trained model( ***s2ad*** model which trained on SCOCO) is also available. please check the readme for more detail.
