### ISSUE TITLE
Checkerboard effects using U-net network

### ISSUE THREAD

**Issue by Mayur28** [vinthony/s2am#12]
Hi,

I've been analyzing the code for the unet generator in unet.py and I am able to produce impressive results, however, it seems that the ConvTranspose2D in UnetSkipConnectionBlock is causing a checkerboard effect. Do you have any indication/idea of how one should go about using bilinear upsampling instead? I've tried experimenting with this myself but I am constantly getting errors with the dimensions of my tensors. 

Any assistance will be highly appreciated.

**Comment by vinthony** [comment]
Thanks for your attention to our paper.
Have you tried to replace the ConvTranspose2D to  Convolution with Upsample and original Convolution?

A post here may help: https://distill.pub/2016/deconv-checkerboard/

**Comment by Mayur28** [comment]
Thanks - I've read that post which gives an excellent intuition of what causes the checkerboard effect and I've tried using an upsampling layer followed by reflection padding and a normal convolution layer. I'm attention to implement an attention guided Unet generator (with skip connections). Thus far, my modified UnetSkipConnectionBlock as follows:

`class UnetSkipConnectionBlock(nn.Module):
    def __init__(self, outer_nc, inner_nc, input_nc=None,
                 submodule=None, outermost=False, innermost=False, norm_layer=nn.BatchNorm2d, opt=None,basicblock=MinimalUnet ): # Has the attention stuff as well... look into it before adding it
        is_attention_layer=False,
        # The additional parameters: attention_model=RASC,basicblock=MinimalUnet,outermostattention=False
        super(UnetSkipConnectionBlock, self).__init__()
        self.outermost = outermost

        if input_nc is None:
            input_nc=outer_nc

        downconv = nn.Conv2d(input_nc, inner_nc, kernel_size=4,
                             stride=2, padding=1)
        downrelu = nn.LeakyReLU(0.2, True)
        downnorm = norm_layer(inner_nc)
        uprelu = nn.ReLU(True)
        upnorm = norm_layer(outer_nc)

        if outermost:

            upsample= nn.Upsample(scale_factor = 2, mode='bilinear')
            reflect= nn.ReflectionPad2d(1)
            conv= nn.Conv2d(2*inner_nc , outer_nc,kernel_size=4, stride=2,padding=1)

            down = [downconv]
            up = [uprelu,upsample,reflect,conv]
            model = basicblock(down,up,submodule,withoutskip=outermost)
        elif innermost:
            upsample= nn.Upsample(scale_factor = 2, mode='bilinear')
            reflect= nn.ReflectionPad2d(1)
            conv= nn.Conv2d(inner_nc, outer_nc,kernel_size=4, stride=2,padding=1)
            down = [downrelu, downconv]
            up = [uprelu, upsample,reflect,conv,upnorm]
            model = basicblock(down,up)
        else:
            upsample= nn.Upsample(scale_factor = 2, mode='bilinear')
            reflect= nn.ReflectionPad2d(1)
            conv= nn.Conv2d(2*inner_nc, outer_nc,kernel_size=4, stride=2,padding=1)
            down = [downrelu, downconv,downnorm]
            up = [uprelu, upsample,reflect,conv, upnorm]

            model = basicblock(down,up,submodule
        self.model =model`

Using this approach, I can't seem to get the sizes of the tensors to be correct as I get the following error: 
`RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 3 and 4 in dimension 2 at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:111`

The MinimalUnet and the rest of the Unet functions are pretty much the same. I've tried various different combinations of how I multiply 'inner_nc' but no luck.

**Comment by vinthony** [comment]
hi, one possible debug idea is to print the accurate feature maps in the forward of basicblock.

Here, I think the key error might be the usage of `reflect`.

Support your tensor get 1x1xchannel after downscaling to the innermost.

When upsampling, your code firstly upsampling the original features to 2x2xchannel by nn.upsample.
Then, a reflectionPad2d will pad the original features to 4x4xchannel.
And a conv2d layer will be used to do the convolution on 4x4xchannel features to 4x4xchannel.

One idea is to remove the `reflect` layer or you can set the padding of conv to 0.

**Comment by Mayur28** [comment]
Hi,

Apologies for the that. That was just included as part of the many things I've tried. I've made the recommended adjustments (I've edited my previous post with the padding taken care of). Unfortunately, this did not solve the problem as I now receive a new error (mentioned in the edited version of my previous post).  I cannot seem to understand why has the tensor now taken a shape of [1,8192,1,1].

P.S I am complete beginner with PyTorch, forgive me if any of my questions seem silly.
Regards

**Comment by vinthony** [comment]
Sorry to reply late.

It is wired and I think the information here is not enough for debugging.

I suggest you print the tensor size in the forward function of MinimalUnet, such as x_out or x_up to observe the actual size of the tensors at each level of Unet.

**Comment by Mayur28** [comment]
No worries. 

I agree that the information provided is insufficient for debugging and it would be quite unreasonable to include all my code.

I will do that. I've now got a few ideas that seem promising and will give them a try in the mean time.

Thanks for your assistance
